"""
Wu Xing (Five Elements) relationships and operations
五行生克关系与操作
"""

from typing import Dict, List, Set, Tuple
from core.types import WuxingType, WuxingRelation, WuxingAttribute


class WuxingSystem:
    """Wu Xing management system for memory dynamics"""
    
    GENERATION_CYCLE = {
        WuxingType.WOOD: WuxingType.FIRE,
        WuxingType.FIRE: WuxingType.EARTH,
        WuxingType.EARTH: WuxingType.METAL,
        WuxingType.METAL: WuxingType.WATER,
        WuxingType.WATER: WuxingType.WOOD
    }
    
    RESTRICTION_CYCLE = {
        WuxingType.WOOD: WuxingType.EARTH,
        WuxingType.EARTH: WuxingType.WATER,
        WuxingType.WATER: WuxingType.FIRE,
        WuxingType.FIRE: WuxingType.METAL,
        WuxingType.METAL: WuxingType.WOOD
    }
    
    def __init__(self, weights: Dict[WuxingType, float] = None):
        self.weights = weights or {
            wuxing: 1.0 for wuxing in WuxingType
        }
        self.balance_history: List[Dict[WuxingType, float]] = []
    
    def get_relation(self, source: WuxingType, target: WuxingType) -> WuxingRelation:
        """Determine the Wu Xing relationship between two elements"""
        if self.GENERATION_CYCLE.get(source) == target:
            return WuxingRelation.GENERATE
        if self.RESTRICTION_CYCLE.get(source) == target:
            return WuxingRelation.RESTRICT
        return WuxingRelation.SAME_NATURE
    
    def get_generated_elements(self, element: WuxingType) -> List[WuxingType]:
        """Get elements generated by this element"""
        generated = []
        for src, tgt in self.GENERATION_CYCLE.items():
            if src == element:
                generated.append(tgt)
        return generated
    
    def get_restricted_elements(self, element: WuxingType) -> List[WuxingType]:
        """Get elements restricted by this element"""
        restricted = []
        for src, tgt in self.RESTRICTION_CYCLE.items():
            if src == element:
                restricted.append(tgt)
        return restricted
    
    def calculate_weight_adjustment(
        self, 
        source_wuxing: WuxingType, 
        target_wuxing: WuxingType,
        activation_level: float = 1.0
    ) -> float:
        """Calculate weight adjustment based on Wu Xing relationship"""
        relation = self.get_relation(source_wuxing, target_wuxing)
        
        base_adjustment = 0.0
        if relation == WuxingRelation.GENERATE:
            base_adjustment = 0.15 * activation_level
        elif relation == WuxingRelation.RESTRICT:
            base_adjustment = -0.10 * activation_level
        
        return base_adjustment
    
    def update_weights(
        self, 
        active_memories: List[Tuple[WuxingType, float]]
    ) -> Dict[WuxingType, float]:
        """Update Wu Xing weights based on active memory patterns"""
        new_weights = self.weights.copy()
        
        for wuxing, activation in active_memories:
            generated = self.get_generated_elements(wuxing)
            restricted = self.get_restricted_elements(wuxing)
            
            for gen_wuxing in generated:
                new_weights[gen_wuxing] += 0.1 * activation * self.weights[wuxing]
            
            for res_wuxing in restricted:
                new_weights[res_wuxing] -= 0.05 * activation * self.weights[wuxing]
        
        for wuxing in WuxingType:
            new_weights[wuxing] = max(0.1, min(2.0, new_weights[wuxing]))
        
        self.weights = new_weights
        self.balance_history.append(new_weights.copy())
        
        if len(self.balance_history) > 100:
            self.balance_history = self.balance_history[-100:]
        
        return new_weights
    
    def get_balance_score(self) -> float:
        """Calculate current system balance (0.0 to 1.0)"""
        values = list(self.weights.values())
        if not values:
            return 0.0
        
        avg = sum(values) / len(values)
        variance = sum((v - avg) ** 2 for v in values) / len(values)
        max_variance = 0.25
        
        balance = 1.0 - min(1.0, variance / max_variance)
        return balance
    
    def suggest_rebalancing(self) -> Dict[WuxingType, float]:
        """Suggest weight adjustments to achieve better balance"""
        balance_score = self.get_balance_score()
        
        if balance_score > 0.8:
            return {}
        
        avg = sum(self.weights.values()) / len(self.weights)
        suggestions = {}
        
        for wuxing, current in self.weights.items():
            if current < avg * 0.8:
                suggestions[wuxing] = avg * 0.9 - current
            elif current > avg * 1.2:
                suggestions[wuxing] = avg * 1.1 - current
        
        return suggestions
    
    def get_wuxing_from_content(self, content: Any) -> WuxingType:
        """Infer Wu Xing type from content characteristics"""
        content_type = type(content).__name__.lower()
        
        wuxing_mapping = {
            'growth': WuxingType.WOOD,
            'create': WuxingType.WOOD,
            'energy': WuxingType.FIRE,
            'passion': WuxingType.FIRE,
            'stability': WuxingType.EARTH,
            'ground': WuxingType.EARTH,
            'decide': WuxingType.METAL,
            'contract': WuxingType.METAL,
            'flow': WuxingType.WATER,
            'wisdom': WuxingType.WATER
        }
        
        for key, wuxing in wuxing_mapping.items():
            if key in content_type:
                return wuxing
        
        return WuxingType.EARTH
    
    def get_compounded_wuxing(self, elements: List[WuxingType]) -> WuxingType:
        """Determine compound Wu Xing from multiple elements"""
        if not elements:
            return WuxingType.EARTH
        
        count = {wuxing: 0 for wuxing in WuxingType}
        for element in elements:
            count[element] += 1
        
        return max(count.items(), key=lambda x: x[1])[0]
